BaseUrl: "https://nkmrya.github.io"
LanguageCode: "en-us"
Title: "Nakamura-Ya"
theme: "aglaus"

Params:
  Author: "NAKAMURA Yasuhiro"
  Birth: "Nov 23, 1994"
  DateForm: "2006-01-02"
  Facebook: "f.nakamura.yasuhiro"
  Github: "nkmrya"
  ShowRelatedPost: True
  SyntaxHighlightTheme: "solarized_dark.min.css"
  ShowTagCloud: True
  Description: "多分Web系を中心に活動してる大学生。元高専生。HaskellやりたいRubyist"
  Icon: "yasuhiro.jpg"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:slug/

MetadataFormat: "yaml"
