BaseUrl: "https://nkmrya.github.com"
LanguageCode: "en-us"
Title: "NAKAMURA-Ya"
theme: "aglaus"

Params:
  Author: "NAKAMURA Yasuhiro"
  Birth: "Nov 23, 1994"
  DateForm: "2006-01-02"
  Facebook: "f.nakamura.yasuhiro"
  Github: "nkmrya"
  ShowRelatedPost: True
  SyntaxHighlightTheme: "solarized_dark.min.css"
  ShowTagCloud: True

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"
